# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3e9d5e284512e54567dd0b9dd19282297e89d392c06137fbf9b1a3b3da2b0f4e12fbe46d056fca167f9b226c3de579f0ce2781823f3ccd6ac3806e0de351c2

test:
  secret_key_base: 852033127426c6b9127304b9f6c097de069014a3f1993e1fc2e9ed9204635b9e48c3fc84ca93b83e312c59529d8ce610cba84c9c445f4f19551aa8b20eff9599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
